// <auto-generated />
using System;
using LoreWeaver.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoreWeaver.Data.Migrations
{
    [DbContext(typeof(LoreWeaverDbContext))]
    [Migration("20260813001033_AddGameSessions")]
    partial class AddGameSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoreWeaver.Data.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("ArmorClassOverride")
                        .HasColumnType("integer");

                    b.Property<int>("CopperPieces")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ElectrumPieces")
                        .HasColumnType("integer");

                    b.Property<int>("GoldPieces")
                        .HasColumnType("integer");

                    b.Property<int>("HitPointsCurrent")
                        .HasColumnType("integer");

                    b.Property<int?>("HitPointsMaxOverride")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PlatinumPieces")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerName")
                        .HasColumnType("text");

                    b.Property<int?>("ProficiencyBonusOverride")
                        .HasColumnType("integer");

                    b.Property<string>("RaceFreeText")
                        .HasColumnType("text");

                    b.Property<string>("RaceIndex")
                        .HasColumnType("text");

                    b.Property<int>("SilverPieces")
                        .HasColumnType("integer");

                    b.Property<string>("SubraceFreeText")
                        .HasColumnType("text");

                    b.Property<string>("SubraceIndex")
                        .HasColumnType("text");

                    b.Property<int>("WorldId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("ClassFreeText")
                        .HasColumnType("text");

                    b.Property<string>("ClassIndex")
                        .HasColumnType("text");

                    b.Property<int?>("HitDieOverride")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStartingClass")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("IX_CharacterClass_OneStartingClassPerCharacter")
                        .HasFilter("\"IsStartingClass\" = true");

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.CharacterSavingThrowProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ability")
                        .HasColumnType("integer");

                    b.Property<int?>("BonusOverride")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProficient")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Ability")
                        .IsUnique();

                    b.ToTable("CharacterSavingThrowProficiencies");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.CharacterSkillProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BonusOverride")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProficient")
                        .HasColumnType("boolean");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Skill")
                        .IsUnique();

                    b.ToTable("CharacterSkillProficiencies");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmorBaseOverride")
                        .HasColumnType("integer");

                    b.Property<int?>("ArmorCategoryOverride")
                        .HasColumnType("integer");

                    b.Property<bool?>("ArmorDexBonusOverride")
                        .HasColumnType("boolean");

                    b.Property<int?>("ArmorMaxBonusOverride")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemFreeText")
                        .HasColumnType("text");

                    b.Property<string>("ItemIndex")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CharacterId" }, "IX_InventoryItem_OneEquippedBodyArmorPerCharacter")
                        .IsUnique()
                        .HasFilter("\"IsEquipped\" = true AND \"Slot\" = 0");

                    b.HasIndex(new[] { "CharacterId" }, "IX_InventoryItem_OneEquippedShieldPerCharacter")
                        .IsUnique()
                        .HasFilter("\"IsEquipped\" = true AND \"Slot\" = 1");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.Character", b =>
                {
                    b.HasOne("LoreWeaver.Data.Entities.World", "World")
                        .WithMany("Characters")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LoreWeaver.Data.Entities.AbilityScoreValue", "Charisma", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModifierOverride")
                                .HasColumnType("integer");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("LoreWeaver.Data.Entities.AbilityScoreValue", "Constitution", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModifierOverride")
                                .HasColumnType("integer");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("LoreWeaver.Data.Entities.AbilityScoreValue", "Dexterity", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModifierOverride")
                                .HasColumnType("integer");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("LoreWeaver.Data.Entities.AbilityScoreValue", "Intelligence", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModifierOverride")
                                .HasColumnType("integer");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("LoreWeaver.Data.Entities.AbilityScoreValue", "Strength", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModifierOverride")
                                .HasColumnType("integer");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("LoreWeaver.Data.Entities.AbilityScoreValue", "Wisdom", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ModifierOverride")
                                .HasColumnType("integer");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Charisma")
                        .IsRequired();

                    b.Navigation("Constitution")
                        .IsRequired();

                    b.Navigation("Dexterity")
                        .IsRequired();

                    b.Navigation("Intelligence")
                        .IsRequired();

                    b.Navigation("Strength")
                        .IsRequired();

                    b.Navigation("Wisdom")
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.CharacterClass", b =>
                {
                    b.HasOne("LoreWeaver.Data.Entities.Character", "Character")
                        .WithMany("Classes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.CharacterSavingThrowProficiency", b =>
                {
                    b.HasOne("LoreWeaver.Data.Entities.Character", "Character")
                        .WithMany("SavingThrows")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.CharacterSkillProficiency", b =>
                {
                    b.HasOne("LoreWeaver.Data.Entities.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("LoreWeaver.Data.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.Character", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Inventory");

                    b.Navigation("SavingThrows");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("LoreWeaver.Data.Entities.World", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
