// <auto-generated />
using LoreWeaver.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoreWeaver.Repository.Migrations
{
    [DbContext(typeof(LoreWeaverContext))]
    [Migration("20250207210615_bancoatt")]
    partial class bancoatt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Mundo", b =>
                {
                    b.Property<int>("MundoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MundoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("DescricaoMundo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeDoMundo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MundoId");

                    b.ToTable("Mundos");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Personagem", b =>
                {
                    b.Property<int>("PersonagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonagemId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("DescricaoPersonagem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MundoId")
                        .HasColumnType("int");

                    b.Property<string>("NomePersonagem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PapelPersonagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonagemId");

                    b.HasIndex("MundoId");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Personagem", b =>
                {
                    b.HasOne("WorldForge.Dominio.Entidades.Mundo", "Mundo")
                        .WithMany("Personagens")
                        .HasForeignKey("MundoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mundo");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Mundo", b =>
                {
                    b.Navigation("Personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
