// <auto-generated />
using System;
using LoreWeaver.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoreWeaver.Repository.Migrations
{
    [DbContext(typeof(LoreWeaverContext))]
    [Migration("20250131211040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoEvento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MundoId")
                        .HasColumnType("int");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EventoId");

                    b.HasIndex("MundoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Mundo", b =>
                {
                    b.Property<int>("MundoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MundoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoMundo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeDoMundo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("MundoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mundos");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Personagem", b =>
                {
                    b.Property<int>("PersonagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonagemId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoPersonagem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("MundoId")
                        .HasColumnType("int");

                    b.Property<string>("NomePersonagem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PapelPersonagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.HasIndex("EventoId");

                    b.HasIndex("MundoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Versao", b =>
                {
                    b.Property<int>("VersaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersaoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoMudancas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MundoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroVersao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VersaoId");

                    b.HasIndex("MundoId");

                    b.ToTable("Versoes");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Evento", b =>
                {
                    b.HasOne("WorldForge.Dominio.Entidades.Mundo", "Mundo")
                        .WithMany("Eventos")
                        .HasForeignKey("MundoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldForge.Dominio.Entidades.Usuario", null)
                        .WithMany("Eventos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Mundo");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Mundo", b =>
                {
                    b.HasOne("WorldForge.Dominio.Entidades.Usuario", null)
                        .WithMany("Mundos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Personagem", b =>
                {
                    b.HasOne("WorldForge.Dominio.Entidades.Evento", "Evento")
                        .WithMany("Personagens")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldForge.Dominio.Entidades.Mundo", "Mundo")
                        .WithMany("Personagens")
                        .HasForeignKey("MundoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WorldForge.Dominio.Entidades.Usuario", null)
                        .WithMany("Personagens")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Evento");

                    b.Navigation("Mundo");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Versao", b =>
                {
                    b.HasOne("WorldForge.Dominio.Entidades.Mundo", "Mundo")
                        .WithMany("Versoes")
                        .HasForeignKey("MundoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mundo");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Evento", b =>
                {
                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Mundo", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Personagens");

                    b.Navigation("Versoes");
                });

            modelBuilder.Entity("WorldForge.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Mundos");

                    b.Navigation("Personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
